"""``parent_record_id`` is a store foreign key, never a surrogate-only preimage.

Provenance defect found 2026-08-29: children generated by the first-improvement
hill-climb (``acquisition.local_search`` / ``CampaignDriver._lean_local_search``)
and by the previous-wave ``prev_top`` elite seeds were stamped with the
``record_id`` of an *unverified pool candidate*.  That id is a well-formed 64-hex
``compute_record_id`` preimage, so nothing ever complained -- but the board was
scored on the surrogate and discarded without reaching MASTER, so no such store
row exists.  Measured over ``dataset == "P"``: 27 of 2,200 ``local`` children and
864 of 1,219 ``elite`` children had a resolvable parent, and
``mine_policy_corpus.build_steps`` silently dropped every unresolved edge (the
two ``fpcamp_minfr_triple_f125*`` campaigns contributed 3 + 10 steps out of 101
non-null parents).

The invariant under test, maintained inductively by every ``Candidate`` producer:

    ``Candidate.parent_record_id`` is ``None`` or the ``record_id`` of a row that
    exists (or is reserved and about to exist) in the store.

Registered claims, one test each:

1. :func:`lineage_anchor` returns a verified candidate's OWN id, and an
   unverified candidate's *parent* id (never the unverified id itself);
2. a CROSS-CASE donor parent keeps its TRUE store id -- it is NOT re-keyed into
   the child's cell (``cross_cell`` in the corpus is what records the mismatch);
3. ``local_search`` over a synthetic elite pool that includes a cross-case donor
   stamps only real store ids -- the regression: pre-fix every child past the
   first hill-climb step named a phantom board;
4. the same for a ``prev_top``-seeded ``build_pool`` wave, driven through the
   anchor resolution ``CampaignDriver._run_wave`` performs;
5. the end-to-end pool invariant: no candidate anywhere names an id that is
   neither ``None`` nor a real store row.
"""

from __future__ import annotations

import random

import numpy as np
import pytest

from lpopt.config import (
    AcquisitionConfig, CaseConfig, DataConfig, ExtractConfig, FlowConfig, FuelConfig,
    LpoptConfig, MasterConfig, ModelConfig, ProduceConfig, RemoteConfig, SearchConfig,
    VerifyConfig,
)
from lpopt.data.schema import compute_record_id
from lpopt.search import acquisition as acq
from lpopt.search.construct import (
    CAMPAIGN_DECK_KNOBS, Candidate, CaseContext, build_pool, candidate_record_id,
)
from lpopt.search.genome import random_genome
from lpopt.search.verify import lineage_anchor

HOT = "P6253Z1G06N24"
MID = "P6253Z2G10N20"
COLD = "P6253Z2G10N24"
DONOR_PAIR = f"{HOT}_{COLD}"                 # the 2-type donor cell
TRIPLE = f"{HOT}_{MID}_{COLD}"               # the graded 3-type campaign cell
FEED = 125
N_FRESH = (FEED - 1) // 4
LIB = "paramA"


def _cfg() -> LpoptConfig:
    return LpoptConfig(
        flow=FlowConfig(), remote=RemoteConfig(), master=MasterConfig(),
        verify=VerifyConfig(), data=DataConfig(),
        case=CaseConfig(pair=DONOR_PAIR, feed=FEED),
        fuel=FuelConfig(), extract=ExtractConfig(), produce=ProduceConfig(),
        search=SearchConfig(), acquisition=AcquisitionConfig(), model=ModelConfig(),
    )


def _ctx() -> CaseContext:
    return CaseContext(pair=DONOR_PAIR, feed=FEED, library_id=LIB, e_core=5.69)


def _pattern(seed: int):
    return random_genome(random.Random(seed), DONOR_PAIR, N_FRESH).to_pattern()


def _donor_elites(n: int = 4):
    """``(true store record_id, Pattern)`` seeds minted in the DONOR cell.

    This is the cross-cell import shape: the id is keyed on ``DONOR_PAIR`` while
    the campaign that mutates the pattern runs in ``TRIPLE``.
    """

    out = []
    for i in range(n):
        pat = _pattern(1000 + i)
        rid = compute_record_id(pat.canonical(), LIB, DONOR_PAIR, CAMPAIGN_DECK_KNOBS)
        out.append((rid, pat))
    return out


def _scored(cands, exploit) -> acq.ScoredPool:
    n = len(cands)
    return acq.ScoredPool(
        candidates=list(cands),
        mean=np.zeros((n, 7)), epistemic=np.zeros((n, 7)), calibrated=np.zeros((n, 7)),
        conv=np.ones(n), p_feas=np.ones(n), acq=np.asarray(exploit, dtype=float),
        raw_epi=np.zeros(n), in_region=np.ones(n, dtype=bool),
        exploit=np.asarray(exploit, dtype=float),
    )


# --------------------------------------------------------------------------- #
# 1. the anchor rule itself
# --------------------------------------------------------------------------- #
def test_anchor_is_self_when_verified_else_parent():
    ctx = _ctx()
    pat = _pattern(1)
    rid = candidate_record_id(pat, ctx)
    cand = Candidate(pat, None, "elite", "PARENT_IN_STORE", rid)

    # verified (its id is in the ledger) -> it IS the anchor.
    assert lineage_anchor(cand, {rid}) == rid
    # unverified -> the anchor is its parent, NEVER its own phantom id.
    assert lineage_anchor(cand, set()) == "PARENT_IN_STORE"
    # unverified with no parent -> no lineage claim at all.
    assert lineage_anchor(Candidate(pat, None, "random", None, rid), set()) is None


# --------------------------------------------------------------------------- #
# 2. a cross-case donor keeps its TRUE id
# --------------------------------------------------------------------------- #
def test_cross_case_donor_id_is_not_rekeyed_into_the_child_cell():
    (donor_rid, donor_pat), = _donor_elites(1)
    triple_ctx = CaseContext(pair=TRIPLE, feed=FEED, library_id=LIB, e_core=5.69)
    rekeyed = compute_record_id(
        donor_pat.canonical(), LIB, TRIPLE, CAMPAIGN_DECK_KNOBS)
    assert rekeyed != donor_rid                       # the two cells differ

    child = Candidate(donor_pat, None, "elite", donor_rid,
                      candidate_record_id(donor_pat, triple_ctx))
    # the donor is a store row, so it anchors on itself under its OWN cell's id.
    assert lineage_anchor(child, {donor_rid}) == donor_rid
    assert lineage_anchor(child, set()) == donor_rid
    assert lineage_anchor(child, {donor_rid}) != rekeyed


# --------------------------------------------------------------------------- #
# 3. the hill-climb regression
# --------------------------------------------------------------------------- #
def test_local_search_children_never_name_an_unverified_board():
    cfg, ctx, rng = _cfg(), _ctx(), random.Random(7)
    elites = _donor_elites(4)
    store_ids = {rid for rid, _ in elites}

    pool = build_pool(ctx, None, elites, set(), rng, cfg, wave_index=0, size=60)
    seeded = [c for c in pool if c.origin == "elite"]
    assert seeded, "the synthetic elite pool must produce elite children"

    scored = _scored(pool, np.linspace(1.0, 0.0, len(pool)))
    # a strictly-improving surrogate so the climb always adopts and recurses:
    # every step past the first is where the phantom id used to be minted.
    step = {"i": 0}

    def score_fn(neighbours):
        step["i"] += 1
        neighbours = list(neighbours)
        base = 100.0 * step["i"]
        return _scored(neighbours, base + np.arange(len(neighbours), dtype=float))

    cfg.search.local_search.top_m = 4
    cfg.search.local_search.neighbors = 5
    cfg.search.local_search.depth = 4
    cfg.search.local_search.max_predictions = 400

    out = acq.local_search(
        None, ctx, scored, None, None, None, cfg.search.local_search, rng,
        set(), score_fn=score_fn,
    )
    locals_ = [c for c in out.candidates if c.origin == "local"]
    assert len(locals_) >= 4, "the climb must recurse past its first step"
    # the regression: every stamped parent is a REAL store row (or None).
    phantom = [c for c in locals_
               if c.parent_record_id is not None
               and c.parent_record_id not in store_ids]
    assert not phantom, (
        f"{len(phantom)}/{len(locals_)} local children name a board that was "
        "never verified and has no store row")
    # ...and the lineage is not simply thrown away.
    assert any(c.parent_record_id in store_ids for c in locals_)


# --------------------------------------------------------------------------- #
# 4. the prev_top regression
# --------------------------------------------------------------------------- #
def test_prev_top_seeds_resolve_through_the_anchor():
    cfg, ctx, rng = _cfg(), _ctx(), random.Random(11)
    elites = _donor_elites(4)
    store_ids = {rid for rid, _ in elites}

    wave0 = build_pool(ctx, None, elites, set(), rng, cfg, wave_index=0, size=60)
    # CampaignDriver keeps the top-ranked CANDIDATES; only some are ever verified.
    prev_top_cands = [c for c in wave0 if c.origin in ("elite", "guided", "random")][:8]
    assert prev_top_cands
    verified_rid = prev_top_cands[0].record_id     # exactly one reached MASTER
    ledger = store_ids | {verified_rid}

    # the resolution _run_wave performs at consumption time
    prev_top = [(lineage_anchor(c, ledger), c.pattern) for c in prev_top_cands]
    assert all(rid is None or rid in ledger for rid, _ in prev_top)
    assert verified_rid in {rid for rid, _ in prev_top}, \
        "a prev_top candidate that WAS verified must anchor on itself"

    wave1 = build_pool(ctx, None, [], ledger, rng, cfg, wave_index=1,
                       prev_top=prev_top, size=60)
    bad = [c for c in wave1
           if c.parent_record_id is not None and c.parent_record_id not in ledger]
    assert not bad, f"{len(bad)} wave-1 children name a phantom prev_top parent"


# --------------------------------------------------------------------------- #
# 4b. ...without shrinking the elite arm
# --------------------------------------------------------------------------- #
def test_shared_anchor_does_not_collapse_the_parent_set():
    """``build_pool`` deduplicates parents by id, so several distinct boards that
    legitimately share ONE anchor must not be collapsed into a single parent --
    that would quietly shrink the elite-mutation arm as a side effect of a
    provenance fix.  The duplicates travel as ``None`` instead (never deduped).
    """

    from lpopt.search.campaign import CampaignDriver

    ctx = _ctx()
    anchor = "REAL_STORE_ROW"
    # four DISTINCT boards, all descended from the same verified ancestor --
    # exactly what a local-search chain produces.
    cands = [
        Candidate(_pattern(200 + i), None, "local", anchor,
                  candidate_record_id(_pattern(200 + i), ctx))
        for i in range(4)
    ]

    class _Driver:
        prev_top = cands
        ledger_ids: set = set()

    seeds = CampaignDriver._prev_top_seeds(_Driver(), set())
    assert len(seeds) == 4, "every carried-forward board must remain a parent"
    # exactly one carries the lineage; the rest are anonymous but still parents.
    assert [rid for rid, _ in seeds] == [anchor, None, None, None]
    assert len({id(p) for _, p in seeds}) == 4

    # an anchor already claimed by a store elite / near-miss seed is not re-emitted
    seeds = CampaignDriver._prev_top_seeds(_Driver(), {anchor})
    assert [rid for rid, _ in seeds] == [None, None, None, None]
    assert len(seeds) == 4


# --------------------------------------------------------------------------- #
# 5. end-to-end pool invariant
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("seed", [0, 3, 17])
def test_pool_parent_ids_are_all_real_or_none(seed):
    cfg, ctx, rng = _cfg(), _ctx(), random.Random(seed)
    elites = _donor_elites(6)
    store_ids = {rid for rid, _ in elites}
    pool = build_pool(ctx, None, elites, set(), rng, cfg, wave_index=0, size=120)
    for c in pool:
        assert c.parent_record_id is None or c.parent_record_id in store_ids, (
            f"{c.origin} candidate names parent {c.parent_record_id!r}, which is "
            "not a store row")
